# Default initial positions for arduinobot's ros2_control fake system

initial_positions:
  torso_joint: 0
  left_joint_1: 0
  left_joint_2: 0
  left_joint_3: 0
  left_joint_4: 0
  left_joint_5: 0
  left_joint_6: 0
  left_gripper_left_claw_joint: 0
  left_gripper_right_claw_joint: 0
  right_joint_1: 0
  right_joint_2: 0
  right_joint_3: 0
  right_joint_4: 0
  right_joint_5: 0
  right_joint_6: 0
  right_gripper_left_claw_joint: 0
  right_gripper_right_claw_joint: 0
  